export const emotionalTones = [
  { name: "Vulnerable", color: "red", emoji: "💔" },
  { name: "Reflective", color: "blue", emoji: "🤔" },
  { name: "Hopeful", color: "green", emoji: "✨" },
  { name: "Joyful", color: "yellow", emoji: "😊" },
  { name: "Nostalgic", color: "purple", emoji: "🕰️" },
  { name: "Grateful", color: "indigo", emoji: "🙏" },
  { name: "Melancholic", color: "gray", emoji: "🌧️" },
  { name: "Empowered", color: "orange", emoji: "💪" },
  { name: "Peaceful", color: "teal", emoji: "🕊️" },
  { name: "Passionate", color: "pink", emoji: "🔥" },
  { name: "Contemplative", color: "slate", emoji: "🧘" },
  { name: "Whimsical", color: "cyan", emoji: "🎭" },
  { name: "Mysterious", color: "violet", emoji: "🔮" },
  { name: "Adventurous", color: "amber", emoji: "🗺️" },
  { name: "Romantic", color: "rose", emoji: "💕" },
  { name: "Humorous", color: "lime", emoji: "😄" },
  { name: "Serious", color: "stone", emoji: "🎯" },
  { name: "Inspiring", color: "emerald", emoji: "🌟" },
  { name: "Curious", color: "sky", emoji: "🔍" },
  { name: "Confident", color: "fuchsia", emoji: "💎" },
  { name: "Gentle", color: "mint", emoji: "🌸" },
  { name: "Intense", color: "crimson", emoji: "⚡" },
  { name: "Dreamy", color: "lavender", emoji: "💭" },
  { name: "Playful", color: "coral", emoji: "🎪" },
  { name: "Horror", color: "black", emoji: "👻" },
  { name: "Fear", color: "gray", emoji: "😱" },
  { name: "Dread", color: "zinc", emoji: "☠️" },
  { name: "Suspense", color: "slate", emoji: "⏳" },
  { name: "Awe", color: "amber", emoji: "😮" },
  { name: "Disgust", color: "lime", emoji: "🤢" },
  { name: "Surprise", color: "yellow", emoji: "😲" },
  { name: "Anger", color: "red", emoji: "😡" },
  { name: "Dark", color: "black", emoji: "🌑" },
  { name: "Light", color: "yellow", emoji: "🌞" },
  { name: "Neutral", color: "gray", emoji: "⚪" },
  { name: "Tragic", color: "rose", emoji: "😭" },
  { name: "Triumphant", color: "emerald", emoji: "🏆" },
  { name: "Creepy", color: "zinc", emoji: "🕷️" },
  { name: "Eerie", color: "violet", emoji: "🦉" },
  { name: "Tense", color: "orange", emoji: "😬" },
  { name: "Uplifting", color: "green", emoji: "🌈" },
  { name: "Sorrowful", color: "blue", emoji: "😢" },
  { name: "Cynical", color: "stone", emoji: "😒" },
  { name: "Optimistic", color: "lime", emoji: "😃" },
  { name: "Pessimistic", color: "gray", emoji: "😔" },
  { name: "Satirical", color: "yellow", emoji: "😏" },
  { name: "Absurd", color: "pink", emoji: "🤪" },
  { name: "Magical", color: "purple", emoji: "🪄" },
  { name: "Epic", color: "amber", emoji: "🦸" },
  { name: "Chilling", color: "blue", emoji: "🥶" },
  { name: "Warm", color: "orange", emoji: "🌅" },
  { name: "Cold", color: "blue", emoji: "❄️" },
  { name: "Violent", color: "red", emoji: "🩸" },
  { name: "Heroic", color: "emerald", emoji: "🦸‍♂️" },
  { name: "Villainous", color: "black", emoji: "🦹" },
  { name: "Mystical", color: "indigo", emoji: "🔮" },
  { name: "Philosophical", color: "slate", emoji: "📚" },
  { name: "Rebellious", color: "red", emoji: "✊" },
  { name: "Subtle", color: "gray", emoji: "🫥" },
  { name: "Blunt", color: "stone", emoji: "🔨" },
];

export const writingStyles = [
  { id: "poetic", name: "Poetic", description: "Lyrical, metaphorical", icon: "🌸" },
  { id: "narrative", name: "Narrative", description: "Storytelling, descriptive", icon: "📖" },
  { id: "conversational", name: "Conversational", description: "Casual, relatable", icon: "💬" },
  { id: "reflective", name: "Reflective", description: "Thoughtful, introspective", icon: "🔍" },
  { id: "journalistic", name: "Journalistic", description: "Clear, factual", icon: "📰" },
  { id: "stream-of-consciousness", name: "Stream of Consciousness", description: "Free-flowing thoughts", icon: "🌊" },
  { id: "letter-format", name: "Letter Format", description: "Personal, intimate", icon: "💌" },
  { id: "dialogue-heavy", name: "Dialogue Heavy", description: "Conversation-driven", icon: "🗣️" },
  { id: "descriptive", name: "Descriptive", description: "Vivid, sensory details", icon: "🎨" },
  { id: "analytical", name: "Analytical", description: "Logical, structured", icon: "📊" },
  { id: "confessional", name: "Confessional", description: "Raw, honest", icon: "💝" },
  { id: "satirical", name: "Satirical", description: "Witty, ironic", icon: "🎭" },
  { id: "minimalist", name: "Minimalist", description: "Simple, concise", icon: "⚪" },
  { id: "experimental", name: "Experimental", description: "Innovative, unique", icon: "🧪" },
  { id: "academic", name: "Academic", description: "Formal, scholarly", icon: "🎓" },
  { id: "creative-nonfiction", name: "Creative Nonfiction", description: "True stories, artistic", icon: "✍️" },
  { id: "fable-like", name: "Fable-like", description: "Moral lessons, allegory", icon: "📚" },
  { id: "diary-entry", name: "Diary Entry", description: "Personal, daily", icon: "📔" },
  { id: "travelogue", name: "Travelogue", description: "Journey-focused", icon: "✈️" },
  { id: "memoir-style", name: "Memoir Style", description: "Life story, reflective", icon: "📖" },
  { id: "essay-format", name: "Essay Format", description: "Structured, argumentative", icon: "📝" },
  { id: "free-verse", name: "Free Verse", description: "Unstructured poetry", icon: "🌿" },
  { id: "haiku-style", name: "Haiku Style", description: "Concise, nature-focused", icon: "🍃" },
  { id: "prose-poetry", name: "Prose Poetry", description: "Poetic prose", icon: "✨" },
  { id: "horror", name: "Horror", description: "Scary, chilling, unsettling", icon: "👻" },
  { id: "thriller", name: "Thriller", description: "Suspenseful, fast-paced", icon: "🔪" },
  { id: "gothic", name: "Gothic", description: "Dark, mysterious, brooding", icon: "🏰" },
  { id: "science-fiction", name: "Science Fiction", description: "Futuristic, speculative", icon: "🤖" },
  { id: "fantasy", name: "Fantasy", description: "Magical, mythical", icon: "🐉" },
  { id: "magical-realism", name: "Magical Realism", description: "Blending reality and magic", icon: "🪄" },
  { id: "urban", name: "Urban", description: "Modern, city-based", icon: "🏙️" },
  { id: "cyberpunk", name: "Cyberpunk", description: "High-tech, dystopian", icon: "🦾" },
  { id: "noir", name: "Noir", description: "Dark, cynical, detective", icon: "🕵️" },
  { id: "romance", name: "Romance", description: "Love stories, relationships", icon: "💖" },
  { id: "comedy", name: "Comedy", description: "Humorous, light-hearted", icon: "😂" },
  { id: "tragedy", name: "Tragedy", description: "Sad, dramatic, emotional", icon: "😭" },
  { id: "adventure", name: "Adventure", description: "Exciting, action-packed", icon: "🏞️" },
  { id: "historical", name: "Historical", description: "Past events, period pieces", icon: "🏺" },
  { id: "mythology", name: "Mythology", description: "Legends, gods, folklore", icon: "⚡" },
  { id: "supernatural", name: "Supernatural", description: "Ghosts, spirits, paranormal", icon: "👻" },
  { id: "epistolary", name: "Epistolary", description: "Told through letters/diaries", icon: "📬" },
  { id: "children", name: "Children's", description: "For young readers", icon: "🧒" },
  { id: "young-adult", name: "Young Adult", description: "Teen-focused themes", icon: "🧑" },
  { id: "satire", name: "Satire", description: "Mocking, critical, witty", icon: "😏" },
  { id: "parody", name: "Parody", description: "Imitative, humorous", icon: "🤣" },
  { id: "fairy-tale", name: "Fairy Tale", description: "Magical, moral lessons", icon: "🧚" },
  { id: "folk-tale", name: "Folk Tale", description: "Traditional, cultural", icon: "🪕" },
  { id: "western", name: "Western", description: "Frontier, cowboy, wild west", icon: "🤠" },
  { id: "detective", name: "Detective", description: "Mystery, investigation", icon: "🕵️‍♂️" },
  { id: "crime", name: "Crime", description: "Law, criminals, justice", icon: "🚓" },
  { id: "psychological", name: "Psychological", description: "Mind, perception, emotion", icon: "🧠" },
  { id: "absurdist", name: "Absurdist", description: "Illogical, surreal, bizarre", icon: "🌀" },
  { id: "slice-of-life", name: "Slice of Life", description: "Everyday, realistic", icon: "☕" },
];

export const lengthOptions = [
  { value: 1, label: "Short", words: "800 words" },
  { value: 2, label: "Medium", words: "1200 words" },
  { value: 3, label: "Long", words: "1800 words" },
]; 